language: java
jdk:
  - openjdk6
  - openjdk7
before_install:
  - sudo apt-get install -qq protobuf-compiler
  - ./src/main/sh/generate_toolchains.sh
install: mvn --toolchains toolchains.xml install -DskipTests=true
script: mvn --toolchains toolchains.xml test
